version: '3'
services:
  web:
    build:
      context: ./web
      dockerfile: Dockerfile
    command: sh run_script.sh
    ports:
      - "8000:8000"
    volumes:
      - ./web/src:/web/src
      - ./volumes/db.sqlite3:/web/db.sqlite3
    environment:
      - DB_PATH=/web/db.sqlite3
      - SUPERUSER=superuser
      - SUPERUSERPASSWORD=superpassword
    depends_on:
      - cache
  cache:
    image: redis