# Generated by Django 2.2.12 on 2020-04-07 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host_addr', models.URLField(max_length=300, unique=True)),
                ('addr_code', models.CharField(blank=True, max_length=200, unique=True)),
            ],
        ),
    ]
