# Generated by Django 2.2.12 on 2020-04-07 07:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shortcut', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='host',
            name='addr_code',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.CreateModel(
            name='Url',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('web_path', models.CharField(max_length=300, unique=True)),
                ('addr_code', models.CharField(blank=True, max_length=200)),
                ('host_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shortcut.Host')),
            ],
        ),
    ]
