# Generated by Django 2.2.12 on 2020-04-07 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shortcut', '0002_auto_20200407_0700'),
    ]

    operations = [
        migrations.RenameField(
            model_name='url',
            old_name='addr_code',
            new_name='path_code',
        ),
    ]
