# Generated by Django 2.2.12 on 2020-04-07 07:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shortcut', '0003_auto_20200407_0702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='url',
            name='host_code',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='shortcut.Host'),
        ),
        migrations.AlterField(
            model_name='url',
            name='web_path',
            field=models.URLField(max_length=300, unique=True),
        ),
    ]
